"""File-level guardrails that keep PRCritiq quiet on noisy or unsafe input.

FR4 requires every skipped file to carry an explicit reason. The checks run in a
fixed precedence so the reported reason is the most informative one available:
safety first, then what the file *is*, then whether it is a language v1 reviews,
and only then how big it is. A huge lockfile is reported as a lockfile, not as an
oversized diff, because the former tells a reader why PRCritiq will never review
it while the latter suggests raising a budget would help.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from enum import StrEnum
from pathlib import PurePosixPath
from typing import Final

from .config import Settings
from .diff import SUPPORTED_LANGUAGES, FileDiff


class GuardrailDecision(StrEnum):
    """Structured guardrail verdicts, per the design Diff Plane."""

    REVIEWABLE = "reviewable"
    SKIPPED_GENERATED = "skipped_generated"
    SKIPPED_LOCKFILE = "skipped_lockfile"
    SKIPPED_VENDOR = "skipped_vendor"
    SKIPPED_BINARY = "skipped_binary"
    SKIPPED_OVERSIZED_FILE = "skipped_oversized_file"
    SKIPPED_OVERSIZED_DIFF = "skipped_oversized_diff"
    SKIPPED_UNSUPPORTED_LANGUAGE = "skipped_unsupported_language"
    SKIPPED_UNSAFE_PATH = "skipped_unsafe_path"


_LOCKFILE_NAMES: Final[frozenset[str]] = frozenset(
    {
        "cargo.lock",
        "composer.lock",
        "conda-lock.yml",
        "flake.lock",
        "gemfile.lock",
        "go.sum",
        "gradle.lockfile",
        "mix.lock",
        "npm-shrinkwrap.json",
        "package-lock.json",
        "packages.lock.json",
        "pdm.lock",
        "pipfile.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "pubspec.lock",
        "uv.lock",
        "yarn.lock",
    }
)

_VENDOR_SEGMENTS: Final[frozenset[str]] = frozenset(
    {
        ".venv",
        "bower_components",
        "external",
        "node_modules",
        "pods",
        "site-packages",
        "third_party",
        "thirdparty",
        "vendor",
        "vendored",
        "venv",
    }
)

_GENERATED_SEGMENTS: Final[frozenset[str]] = frozenset(
    {
        "__generated__",
        "__pycache__",
        ".next",
        ".nuxt",
        "build",
        "coverage",
        "dist",
        "generated",
        "out",
    }
)

_GENERATED_SUFFIXES: Final[tuple[str, ...]] = (
    ".designer.cs",
    ".g.dart",
    ".g.ts",
    ".generated.go",
    ".generated.ts",
    ".map",
    ".min.css",
    ".min.js",
    ".pb.go",
    ".snap",
    "_pb2.py",
    "_pb2_grpc.py",
)

# Deliberately specific. A bare "DO NOT EDIT" appears in ordinary prose and in
# test fixtures, so only conventional generator banners count here.
_GENERATED_MARKER: Final = re.compile(
    r"@generated\b|code generated by|do not edit this file|"
    r"automatically generated by|autogenerated by",
    re.IGNORECASE,
)

_BINARY_SUFFIXES: Final[frozenset[str]] = frozenset(
    {
        ".bmp",
        ".bz2",
        ".class",
        ".dll",
        ".dylib",
        ".eot",
        ".exe",
        ".gif",
        ".gz",
        ".ico",
        ".jar",
        ".jpeg",
        ".jpg",
        ".mp3",
        ".mp4",
        ".o",
        ".onnx",
        ".otf",
        ".parquet",
        ".pdf",
        ".png",
        ".pyc",
        ".so",
        ".sqlite",
        ".tar",
        ".ttf",
        ".wasm",
        ".webp",
        ".woff",
        ".woff2",
        ".zip",
    }
)

_UNSAFE_SEGMENTS: Final[frozenset[str]] = frozenset({"..", ".git"})


@dataclass(frozen=True)
class GuardrailOutcome:
    """One guardrail verdict with the reason a reader needs."""

    path: str
    decision: GuardrailDecision
    reason: str

    @property
    def reviewable(self) -> bool:
        return self.decision is GuardrailDecision.REVIEWABLE


def _segments(path: str) -> tuple[str, ...]:
    return tuple(part.lower() for part in PurePosixPath(path).parts)


def _unsafe_path_reason(path: str) -> str | None:
    if not path.strip():
        return "the path is empty"
    if "\x00" in path or any(ord(char) < 32 for char in path):
        return "the path contains control characters"
    if "\\" in path:
        return "the path contains a backslash, which GitHub never emits for a repository path"
    if path.startswith("/"):
        return "the path is absolute"
    if re.match(r"^[A-Za-z]:", path):
        return "the path carries a drive letter"
    unsafe = _UNSAFE_SEGMENTS.intersection(_segments(path))
    if unsafe:
        return f"the path traverses a forbidden segment: {sorted(unsafe)[0]}"
    return None


def _is_generated(file_diff: FileDiff) -> str | None:
    lowered = file_diff.path.lower()
    if lowered.endswith(_GENERATED_SUFFIXES):
        return "the filename matches a generated-artifact convention"
    marked = _GENERATED_SEGMENTS.intersection(_segments(file_diff.path)[:-1])
    if marked:
        return f"the file sits in a generated output directory: {sorted(marked)[0]}"
    if file_diff.patch and _GENERATED_MARKER.search(file_diff.patch):
        return "the patch carries a generator banner"
    return None


def evaluate_file(file_diff: FileDiff, settings: Settings) -> GuardrailOutcome:
    """Return the guardrail verdict for one changed file."""

    path = file_diff.path

    unsafe = _unsafe_path_reason(path)
    if unsafe is not None:
        return GuardrailOutcome(path, GuardrailDecision.SKIPPED_UNSAFE_PATH, unsafe)

    suffix = PurePosixPath(path).suffix.lower()
    if suffix in _BINARY_SUFFIXES:
        return GuardrailOutcome(
            path,
            GuardrailDecision.SKIPPED_BINARY,
            f"{suffix} is a binary format with no reviewable text",
        )

    if PurePosixPath(path).name.lower() in _LOCKFILE_NAMES:
        return GuardrailOutcome(
            path,
            GuardrailDecision.SKIPPED_LOCKFILE,
            "dependency lockfiles are resolver output, not authored code",
        )

    vendored = _VENDOR_SEGMENTS.intersection(_segments(path)[:-1])
    if vendored:
        return GuardrailOutcome(
            path,
            GuardrailDecision.SKIPPED_VENDOR,
            f"the file is vendored third-party code under {sorted(vendored)[0]}/",
        )

    generated = _is_generated(file_diff)
    if generated is not None:
        return GuardrailOutcome(path, GuardrailDecision.SKIPPED_GENERATED, generated)

    if file_diff.language not in SUPPORTED_LANGUAGES:
        return GuardrailOutcome(
            path,
            GuardrailDecision.SKIPPED_UNSUPPORTED_LANGUAGE,
            f"v1 reviews {', '.join(sorted(SUPPORTED_LANGUAGES))}, not {file_diff.language}",
        )

    if file_diff.patch is not None:
        patch_bytes = len(file_diff.patch.encode("utf-8"))
        if patch_bytes > settings.max_file_bytes:
            return GuardrailOutcome(
                path,
                GuardrailDecision.SKIPPED_OVERSIZED_FILE,
                f"the patch is {patch_bytes} bytes, over the {settings.max_file_bytes}-byte budget",
            )

    # Checked before the line budget: a missing patch is the harder blocker,
    # since raising a budget cannot recover text GitHub never sent.
    if file_diff.patch is None and file_diff.changes > 0:
        return GuardrailOutcome(
            path,
            GuardrailDecision.SKIPPED_OVERSIZED_DIFF,
            "GitHub served no patch for this file, which it does when a diff is too large",
        )

    if file_diff.changes > settings.max_diff_lines:
        return GuardrailOutcome(
            path,
            GuardrailDecision.SKIPPED_OVERSIZED_DIFF,
            f"the file changes {file_diff.changes} lines, over the "
            f"{settings.max_diff_lines}-line budget",
        )

    return GuardrailOutcome(path, GuardrailDecision.REVIEWABLE, "the file is in scope for review")


def apply_guardrails(
    file_diffs: Sequence[FileDiff] | Iterable[FileDiff],
    settings: Settings,
) -> tuple[GuardrailOutcome, ...]:
    """Evaluate every changed file and enforce the pull-request file budget.

    Files are judged individually first, then the budget is applied to the
    survivors in order. A pull request that changes more reviewable files than
    the budget allows keeps the first `max_files` of them and reports the rest
    honestly instead of reviewing an arbitrary subset in silence.
    """

    outcomes: list[GuardrailOutcome] = []
    kept = 0
    for file_diff in file_diffs:
        outcome = evaluate_file(file_diff, settings)
        if outcome.reviewable:
            if kept >= settings.max_files:
                outcome = GuardrailOutcome(
                    outcome.path,
                    GuardrailDecision.SKIPPED_OVERSIZED_DIFF,
                    f"the pull request exceeds the {settings.max_files}-reviewable-file budget",
                )
            else:
                kept += 1
        outcomes.append(outcome)
    return tuple(outcomes)


def reviewable_files(
    file_diffs: Sequence[FileDiff],
    outcomes: Sequence[GuardrailOutcome],
) -> tuple[FileDiff, ...]:
    """Select the file diffs their paired outcomes marked reviewable."""

    if len(file_diffs) != len(outcomes):
        raise ValueError("file diffs and guardrail outcomes must be the same length")
    return tuple(
        file_diff
        for file_diff, outcome in zip(file_diffs, outcomes, strict=True)
        if outcome.reviewable
    )
