"""Tests for the file guardrail gate."""

from __future__ import annotations

import pytest

from prcritiq.config import Settings
from prcritiq.diff import FileDiff, build_file_diff
from prcritiq.guardrails import (
    GuardrailDecision,
    GuardrailOutcome,
    apply_guardrails,
    evaluate_file,
    reviewable_files,
)

SETTINGS = Settings(max_files=30, max_diff_lines=2000, max_file_bytes=250_000)


def diff_for(
    path: str,
    *,
    patch: str | None = "@@ -1,1 +1,2 @@\n alpha\n+beta\n",
    changes: int = 1,
    status: str = "modified",
) -> FileDiff:
    return build_file_diff(
        path=path,
        status=status,
        additions=changes,
        deletions=0,
        changes=changes,
        patch=patch,
    )


def decide(path: str, **kwargs: object) -> GuardrailOutcome:
    return evaluate_file(diff_for(path, **kwargs), SETTINGS)  # type: ignore[arg-type]


class TestReviewable:
    @pytest.mark.parametrize("path", ["src/app.py", "web/main.ts", "web/widget.jsx"])
    def test_supported_source_files_are_reviewable(self, path: str) -> None:
        assert decide(path).decision is GuardrailDecision.REVIEWABLE


class TestUnsafePaths:
    @pytest.mark.parametrize(
        "path",
        [
            "../outside/secrets.py",
            "/etc/passwd.py",
            "C:/Windows/system.py",
            "src\\windows\\style.py",
            ".git/config.py",
            "   ",
        ],
    )
    def test_unsafe_paths_are_skipped(self, path: str) -> None:
        assert decide(path).decision is GuardrailDecision.SKIPPED_UNSAFE_PATH

    def test_unsafe_path_outranks_every_other_check(self) -> None:
        """Safety is evaluated before the file is classified or measured."""

        outcome = decide("../node_modules/uv.lock")

        assert outcome.decision is GuardrailDecision.SKIPPED_UNSAFE_PATH


class TestFileIdentity:
    @pytest.mark.parametrize("path", ["assets/logo.png", "dist/app.wasm", "lib/native.so"])
    def test_binary_extensions_are_skipped(self, path: str) -> None:
        assert decide(path).decision is GuardrailDecision.SKIPPED_BINARY

    @pytest.mark.parametrize("path", ["uv.lock", "package-lock.json", "backend/go.sum"])
    def test_lockfiles_are_skipped(self, path: str) -> None:
        assert decide(path).decision is GuardrailDecision.SKIPPED_LOCKFILE

    @pytest.mark.parametrize(
        "path", ["node_modules/left-pad/index.js", "vendor/github.com/pkg/errors.py"]
    )
    def test_vendored_code_is_skipped(self, path: str) -> None:
        assert decide(path).decision is GuardrailDecision.SKIPPED_VENDOR

    @pytest.mark.parametrize("path", ["static/app.min.js", "api/service_pb2.py", "web/bundle.map"])
    def test_generated_filenames_are_skipped(self, path: str) -> None:
        assert decide(path).decision is GuardrailDecision.SKIPPED_GENERATED

    def test_generated_output_directories_are_skipped(self) -> None:
        assert decide("dist/bundle.js").decision is GuardrailDecision.SKIPPED_GENERATED

    def test_generator_banner_in_the_patch_is_skipped(self) -> None:
        patch = "@@ -1,1 +1,2 @@\n alpha\n+# Code generated by protoc. DO NOT EDIT.\n"

        assert decide("src/models.py", patch=patch).decision is GuardrailDecision.SKIPPED_GENERATED

    def test_ordinary_prose_does_not_trip_the_generator_banner(self) -> None:
        """A tight marker list keeps hand-written warnings reviewable."""

        patch = '@@ -1,1 +1,2 @@\n alpha\n+RULES = "DO NOT EDIT while the lock is held"\n'

        assert decide("src/models.py", patch=patch).decision is GuardrailDecision.REVIEWABLE

    def test_a_directory_named_like_output_does_not_skip_the_file_itself(self) -> None:
        """Only parent segments are matched, so a file named build.py stays reviewable."""

        assert decide("src/build.py").decision is GuardrailDecision.REVIEWABLE


class TestLanguageSupport:
    @pytest.mark.parametrize("path", ["README.md", "cmd/main.go", "infra/main.tf", "Makefile"])
    def test_unsupported_languages_are_skipped(self, path: str) -> None:
        outcome = decide(path)

        assert outcome.decision is GuardrailDecision.SKIPPED_UNSUPPORTED_LANGUAGE


class TestSizeBudgets:
    def test_oversized_patch_bytes_are_skipped(self) -> None:
        settings = Settings(max_file_bytes=200)
        big = "@@ -1,1 +1,101 @@\n alpha\n" + "+padding\n" * 100

        outcome = evaluate_file(diff_for("src/app.py", patch=big, changes=100), settings)

        assert outcome.decision is GuardrailDecision.SKIPPED_OVERSIZED_FILE

    def test_oversized_change_count_is_skipped(self) -> None:
        settings = Settings(max_diff_lines=10)

        outcome = evaluate_file(diff_for("src/app.py", changes=999), settings)

        assert outcome.decision is GuardrailDecision.SKIPPED_OVERSIZED_DIFF

    def test_missing_patch_for_a_supported_file_is_an_oversized_diff(self) -> None:
        """GitHub omits the patch when a text diff is too large to serve."""

        outcome = decide("src/app.py", patch=None, changes=5000)

        assert outcome.decision is GuardrailDecision.SKIPPED_OVERSIZED_DIFF
        assert "no patch" in outcome.reason

    def test_identity_outranks_size(self) -> None:
        """A huge lockfile reads as a lockfile, not as a budget a reader could raise."""

        settings = Settings(max_diff_lines=10, max_file_bytes=50)

        outcome = evaluate_file(diff_for("uv.lock", changes=9999), settings)

        assert outcome.decision is GuardrailDecision.SKIPPED_LOCKFILE


class TestPullRequestBudget:
    def test_reviewable_files_beyond_the_budget_are_reported_not_dropped(self) -> None:
        settings = Settings(max_files=2)
        diffs = [diff_for(f"src/mod_{index}.py") for index in range(4)]

        outcomes = apply_guardrails(diffs, settings)

        assert [item.decision for item in outcomes] == [
            GuardrailDecision.REVIEWABLE,
            GuardrailDecision.REVIEWABLE,
            GuardrailDecision.SKIPPED_OVERSIZED_DIFF,
            GuardrailDecision.SKIPPED_OVERSIZED_DIFF,
        ]
        assert "2-reviewable-file budget" in outcomes[3].reason

    def test_skipped_files_do_not_consume_the_budget(self) -> None:
        settings = Settings(max_files=2)
        diffs = [
            diff_for("README.md"),
            diff_for("src/first.py"),
            diff_for("uv.lock"),
            diff_for("src/second.py"),
        ]

        outcomes = apply_guardrails(diffs, settings)

        assert outcomes[1].reviewable is True
        assert outcomes[3].reviewable is True

    def test_reviewable_files_selects_the_paired_diffs(self) -> None:
        diffs = [diff_for("src/app.py"), diff_for("README.md")]

        outcomes = apply_guardrails(diffs, SETTINGS)

        assert [item.path for item in reviewable_files(diffs, outcomes)] == ["src/app.py"]

    def test_mismatched_lengths_are_rejected(self) -> None:
        with pytest.raises(ValueError, match="same length"):
            reviewable_files([diff_for("src/app.py")], ())
